### ISSUE TITLE
Touch input still crashing on 4.16.7 and 4.17.1-1 Debian Buster

### ISSUE THREAD

**Issue by ardynn** [jakeday/linux-surface#203] opened 2018-06-17 07:46 UTC
I upgraded to the new kernel using the instructions on the main page. It seems to be stable a bit longer, but after about twenty minutes or so touch crashes.

I'm on Debian Buster. Surface Book with performance base.

**Comment by Wesley-VanNeck** [comment] 2018-06-18 14:06
same on surface pro 4 on ubuntu 16.04.4

**Comment by Wesley-VanNeck** [comment] 2018-06-18 14:07
it seems more stabble but it crases if there is a work around for it  plz let me hear it

**Comment by ardynn** [comment] 2018-06-19 00:11
Since I made this, I've realized it seems to happen a lot more in landscape mode. In fact, in some cases after a minute or two.

**Comment by Wesley-VanNeck** [comment] 2018-06-19 10:38
I noticed it to

**Comment by electrikjesus** [comment] 2018-06-20 15:11
This behavior is also still present on Android as well with Kernel-4.16.8 & 4.16.14 (Surface Book)

**Comment by Wesley-VanNeck** [comment] 2018-06-27 06:35
It seems to be working fine on ubuntu 17.10.1

**Comment by jakeday** [comment] 2018-06-28 18:03
This is due to kernels 4.16+ and how they handle different contexts for guc clients. I'll have to re-work that part of the driver. You'll run into it when having too high of activity.

**Comment by jakeday** [comment] 2018-06-28 22:41
Closing this as it's a duplicate of #171

**Closed by jakeday** 2018-06-28 22:41 UTC
