### ISSUE TITLE
SB2: intel_power_well_enable error

### ISSUE THREAD

**Issue by calidor** [jakeday/linux-surface#173] opened 2018-05-12 07:12 UTC
Surface Book 2: 15 inch 

dmesg keeps spamming: 
 31.892775] ------------[ cut here ]------------
[   31.892776] WARN_ON(intel_cdclk_needs_modeset(&dev_priv->cdclk.hw, &cdclk_state))
[   31.892827] WARNING: CPU: 7 PID: 1286 at drivers/gpu/drm/i915/intel_runtime_pm.c:720 gen9_dc_off_power_well_enable+0x1ed/0x240 [i915]
[   31.892828] Modules linked in: btusb btrtl btbcm btintel bluetooth ecdh_generic snd_hda_codec_hdmi input_leds 8250_dw intel_rapl x86_pkg_temp_thermal intel_powerclamp snd_hda_codec_realtek coretemp snd_hda_codec_generic joydev binfmt_misc nls_iso8859_1 kvm_intel kvm irqbypass intel_cstate idma64 mwifiex_pcie intel_rapl_perf virt_dma snd_hda_intel nouveau mwifiex snd_hda_codec snd_hda_core pcspkr snd_hwdep snd_pcm snd_timer cfg80211 hid_sensor_rotation hid_sensor_gyro_3d snd hid_sensor_accel_3d nvidiafb hid_sensor_als hid_sensor_trigger mxm_wmi vgastate industrialio_triggered_buffer wmi kfifo_buf fb_ddc iTCO_wdt hid_sensor_iio_common ttm soundcore iTCO_vendor_support intel_lpss_pci processor_thermal_device industrialio mei_me intel_lpss shpchp intel_pch_thermal intel_soc_dts_iosf evbug mac_hid int3403_thermal
[   31.892861]  int3400_thermal tpm_crb int340x_thermal_zone acpi_thermal_rel surface_acpi soc_button_array dptf_power surfacepro3_button acpi_pad ip_tables x_tables autofs4 intel_ipts mei i2c_hid hid_multitouch usbhid hid_sensor_hub hid_generic intel_ishtp_hid hid crct10dif_pclmul crc32_pclmul ghash_clmulni_intel i915 pcbc i2c_algo_bit drm_kms_helper aesni_intel syscopyarea sysfillrect aes_x86_64 sysimgblt crypto_simd fb_sys_fops glue_helper cryptd drm i2c_i801 intel_ish_ipc intel_ishtp pinctrl_sunrisepoint video pinctrl_intel
[   31.892886] CPU: 7 PID: 1286 Comm: Xorg Tainted: G        W        4.16.7-surface-linux-surface #63
[   31.892888] Hardware name: Microsoft Corporation Surface Book 2/Surface Book 2, BIOS 388.1932.769 12/12/2017
[   31.892906] RIP: 0010:gen9_dc_off_power_well_enable+0x1ed/0x240 [i915]
[   31.892908] RSP: 0018:ffffadce026cb9e0 EFLAGS: 00010286
[   31.892909] RAX: 0000000000000000 RBX: ffff9ec314eb8000 RCX: ffffffff92062f08
[   31.892910] RDX: 0000000000000001 RSI: 0000000000000096 RDI: 0000000000000247
[   31.892911] RBP: ffffadce026cba00 R08: 0000000000000f21 R09: ffffffff925484c0
[   31.892912] R10: 0000000000000040 R11: 0000000000000000 R12: ffff9ec314eb8000
[   31.892913] R13: 0000000400000000 R14: aaaaaaaaaaaaaaab R15: 0000000000000022
[   31.892914] FS:  00007f92ea17fa40(0000) GS:ffff9ec32f5c0000(0000) knlGS:0000000000000000
[   31.892915] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   31.892917] CR2: 00007f92da68d000 CR3: 0000000427f54006 CR4: 00000000003606e0
[   31.892918] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[   31.892919] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[   31.892919] Call Trace:
[   31.892936]  intel_power_well_enable+0x40/0x50 [i915]
[   31.892953]  __intel_display_power_get_domain+0x82/0xa0 [i915]
[   31.892969]  intel_display_power_get+0x33/0x50 [i915]
[   31.892988]  i915_gem_request_alloc+0x30f/0x420 [i915]
[   31.893007]  i915_gem_do_execbuffer+0x633/0x1100 [i915]
[   31.893011]  ? default_wake_function+0x12/0x20
[   31.893014]  ? pollwake+0x72/0x90
[   31.893017]  ? __wake_up_sync_key+0x1e/0x30
[   31.893020]  ? sock_def_readable+0x40/0x70
[   31.893022]  ? unix_stream_sendmsg+0x36d/0x3b0
[   31.893039]  i915_gem_execbuffer2+0x1f8/0x3a0 [i915]
[   31.893056]  ? i915_gem_execbuffer+0x2d0/0x2d0 [i915]
[   31.893066]  drm_ioctl_kernel+0x5f/0xb0 [drm]
[   31.893075]  drm_ioctl+0x31b/0x3d0 [drm]
[   31.893090]  ? i915_gem_execbuffer+0x2d0/0x2d0 [i915]
[   31.893093]  do_vfs_ioctl+0xa8/0x620
[   31.893095]  ? handle_mm_fault+0xe3/0x220
[   31.893098]  SyS_ioctl+0x79/0x90
[   31.893100]  do_syscall_64+0x73/0x130
[   31.893103]  entry_SYSCALL_64_after_hwframe+0x3d/0xa2
[   31.893104] RIP: 0033:0x7f92e7598f07
[   31.893105] RSP: 002b:00007ffc1da61bb8 EFLAGS: 00003246 ORIG_RAX: 0000000000000010
[   31.893107] RAX: ffffffffffffffda RBX: 00007f92ea0e6000 RCX: 00007f92e7598f07
[   31.893108] RDX: 00007ffc1da61be0 RSI: 0000000040406469 RDI: 000000000000000d
[   31.893109] RBP: 000000000000000d R08: 0000000000003a50 R09: 0000000000000002
[   31.893109] R10: 00007f92ea1a1000 R11: 0000000000003246 R12: 00007ffc1da61be0
[   31.893110] R13: 0000000000003000 R14: 0000000000000630 R15: 000000000000d000
[   31.893112] Code: 85 d2 0f 8e d7 fe ff ff 8b 71 24 48 89 df e8 4b fa 06 00 e9 c7 fe ff ff 48 c7 c6 40 2a 88 c0 48 c7 c7 02 31 87 c0 e8 63 16 51 d0 <0f> 0b e9 6e fe ff ff 89 c6 48 c7 c7 88 2a 88 c0 e8 4e 16 51 d0 
[   31.893142] ---[ end trace 592f7e1a6ab45112 ]---

This leads to k isntability, crash.

**Comment by calidor** [comment] 2018-05-12 07:18
kernel 16.7

**Comment by versipellis** [comment] 2018-05-16 19:49
Noticing that this does happen more frequently if I have too many Firefox tabs open (4 windows @ 66 tabs total seems to happen with some regularity)

**Comment by vonAlenberg** [comment] 2018-05-28 09:28
Do you use Ubuntu with GNOME? If so try to disable Gnome extensions, they cause some problems.

**Comment by calidor** [comment] 2018-05-28 20:32
iuse kali with gnome :) ill try that

**Comment by jakeday** [comment] 2018-06-07 02:21
Duplicate of #176

**Closed by jakeday** 2018-06-07 02:21 UTC
