### ISSUE TITLE
Surface Book 2 15": No Battery Reading Ubuntu 16.10

### ISSUE THREAD

**Issue by ShantanuJoshi** [jakeday/linux-surface#58] opened 2017-12-13 08:01 UTC
Unable to get any battery or power reading. Upower gives battery-missing-symbolic. No battery power options in Ubuntu settings. Any fixes on this?

**Comment by jakeday** [comment] 2017-12-13 20:06
This is a duplicate of #28

**Closed by jakeday** 2017-12-13 20:06 UTC
