### ISSUE TITLE
Surface Go - Touch Screen

### ISSUE THREAD

**Issue by tuurleyck** [jakeday/linux-surface#250] opened 2018-09-18 13:54 UTC
I ran the setup on my Surface Go to patch and resolve the WiFi issues with Atheros.
After the patch, my touchscreen doesn't work anymore and I'm not able to revert, by going back to another kernel version.

I'd like to resolve this, do you have any pointers ?

**Comment by taichichuan** [comment] 2018-09-20 02:33
FWIW, with 4.18.7, my configuration changes to reenable the SD card reader and the Atheros firmware fixes, I have a completely functional Surface Go.  Touch screen works although I haven't tried much in the way of  multi-touch on it, Wi-Fi, suspend, the external keyboard, touchpad and stylus and the USB-C works with external USB hub, Ethernet, card reader adapter.  Audio works and I can suspend from the menu and resume with everything working after resume.  However, just closing the tablet doesn't seem to get detected as a suspend.  And, florence (virtual keyboard) works with stylus if the keyboard isn't connected.  This is running Linux Mint 19 with jakeday's 4.18.7 kernel.

**Comment by mklnz** [comment] 2018-09-20 02:39
@tuurleyck I'm having the same problem, to be honest out of the box the touch screen and scrolling works great, after switching to 4.18.7 surface kernel I'm no longer able to use the touch screen and two finger scrolling on the trackpad no longer works.

Using elementary OS 5.0 based on Ubuntu 18.04, also tried vanilla Ubuntu 18.04 - same issue.

**Comment by tuurleyck** [comment] 2018-09-20 19:48
I went from Ubuntu Budie and kernel 4.15.0 to jakeday's 4.18.7 kernel.
Not sure how to proceed, might revert back and try to patch with the fix to enable WiFi only.

But happy to contribute where I can to get to a solution, since I don't seem to be the only one @mklnz !

@taichichuan , do you see additional ipts devices for touchscreen and pen&stylus when performing xinput ?

`$ xinput
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ Microsoft Surface Type Cover Consumer Control	id=9	[slave  pointer  (2)]
⎜   ↳ Microsoft Surface Type Cover Touchpad   	id=14	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Video Bus                               	id=6	[slave  keyboard (3)]
    ↳ Power Button                            	id=7	[slave  keyboard (3)]
    ↳ Intel HID events                        	id=11	[slave  keyboard (3)]
    ↳ Intel HID 5 button array                	id=12	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=13	[slave  keyboard (3)]
    ↳ Microsoft Surface Type Cover            	id=8	[slave  keyboard (3)]
    ↳ Microsoft Surface Type Cover Consumer Control	id=10	[slave  keyboard (3)]`

**Comment by jakeday** [comment] 2018-10-02 13:57
Fixed in 4.18.11.

**Closed by jakeday** 2018-10-02 13:57 UTC

**Comment by tuurleyck** [comment] 2018-10-06 16:19
Not for me, unfortunately. Re-installed Ubuntu from scratch and applied latest release.

**Comment by rm1138** [comment] 2019-01-01 10:11
I also has the same problem, with fresh install Ubuntu 18.10.
Tried the latest 4.18.20 kernel and 4.18.16.

**Comment by bassjacob** [comment] 2019-02-06 14:21
I can confirm that [rm1138's patch](https://github.com/jakeday/linux-surface/issues/250#issuecomment-450741197) works, even when applied to the file at `/etc/udev/rules.d/98-keyboardscovers.rules` and not to the file in the kernel source.

while using the latest stable kernel, I applied that patch the file in `/etc` and rebooted and all seems to be working
