### ISSUE TITLE
Surface Book 2: Battery overheating

### ISSUE THREAD

**Issue by atharos1** [jakeday/linux-surface#83] opened 2018-01-29 18:54 UTC
Hi! I'm a bit of a noob, trying Ubuntu 17.10 on my 15' Surface Book 2. Other than the know issues, I find the cumputer heats up quite a lot, specially the base. I'm just running Firefox, so the GPU shuldn't be in use. The top portion also heats up, but nearly as much.
The device is currently plugged in.

Thanks!

**Comment by jakeday** [comment] 2018-01-31 00:45
@atharos1 This is a known issue with the SB2 and the 4.14 kernel series. This will be fixed in 4.15 which I'll be working on tonight.

**Comment by jakeday** [comment] 2018-02-02 03:44
This is the same root cause as #65 and I'll address it there.

**Closed by jakeday** 2018-02-02 03:44 UTC
Labels: bug
