### ISSUE TITLE
Can't upgrade from 5.1.15 to 5.2.x, 5.3.x

### ISSUE THREAD

**Issue by hbh7** [jakeday/linux-surface#598] opened 2019-11-02 05:33 UTC
Hey all, 
I started off here with the kernel from this repo, but later discovered qzed's more up to date one, and wanted to switch to that. Unfortunately I've run into a few issues...

Running Arch on a Surface Book 2 13" 

Installing the prebuilt kernels from https://github.com/qzed/linux-surface/releases gives me errors installing every module, ex: 
```
==> dkms install wireguard/0.0.20191012 -k 5.3.6-1-surface
Error! Bad return status for module build on kernel: 5.3.6-1-surface (x86_64)
Consult /var/lib/dkms/wireguard/0.0.20191012/build/make.log for more information.
```
Checking those files and the culprit seems to be `cc1: error: incompatible gcc/plugin versions`

I've tried a few of the various setup scripts such as https://github.com/qzed/linux-surface/blob/master/setup.sh and the one here https://github.com/dmhacker/arch-linux-surface with adjusted repo paths, but no luck still. 

Not really sure what's up, or where to go from here. Happy to provide any more info. Thanks!

**Comment by qzed** [comment] 2019-11-03 00:38
This issue is caused by a gcc update on Arch, basically the gcc kernel with which the kernel was built is incompatible with the gcc used when building the modules via dkms.

I've uploaded some new releases. Should be fixed.

**Closed by qzed** 2019-11-03 00:38 UTC

**Comment by hbh7** [comment] 2019-11-03 02:25
Working good now, thank you!
