### ISSUE TITLE
ubuntu 18.04, everything did not work after suspend

### ISSUE THREAD

**Issue by Faterjames** [jakeday/linux-surface#191] opened 2018-06-01 09:50 UTC
can not touch screen , no wifi 
and it seems that the camera can not work in ubuntu 18.04

**Comment by vonAlenberg** [comment] 2018-06-04 06:37
Yes, this happens after suspend. Somehow Ubuntu starts flight-mode and disables all Wi-Fi.

**Comment by jakeday** [comment] 2018-06-07 02:34
Duplicate of #166

**Closed by jakeday** 2018-06-07 02:34 UTC
