### ISSUE TITLE
Surface pen not working

### ISSUE THREAD

**Issue by reaganch** [jakeday/linux-surface#22] opened 2017-11-01 02:02 UTC
I'm running Linux Mint 18.2 on a Surface Pro 4.
I just installed the 4.14.0-rc7 kernel and followed all your instructions from the readme, and although the touchscreen works, I cannot seem to get my surface pen to work. I tried the command "sudo echo 1 > /sys/kernel/debug/ipts/mode" to enable multi-touch, as inferred from discussions at https://www.reddit.com/r/SurfaceLinux/comments/6tbnqx/jakedays_kernel_for_surface_bookpro_4, which successfully modified the file /sys/kernel/debug/ipts/mode, but as soon as I execute the command, both touchscreen and the surface pen don't work. The computer also hangs if I try to restart or shut down after doing this. The next time it reboots, /sys/kernel/debug/ipts/mode is reverted back to 0.
Any ideas what I may be doing wrong here? I also have cantenna's superkerneltouch+ kernel installed and my surface pen works just fine with it.

**Comment by geoffholden** [comment] 2017-11-01 16:55
This is a duplicate of #8

**Comment by jakeday** [comment] 2017-11-01 17:25
@geoffholden Agreed.

**Closed by jakeday** 2017-11-01 17:25 UTC
