### ISSUE TITLE
Surface Devices: Fan control and Thermal support

### ISSUE THREAD

**Issue by realSpok** [jakeday/linux-surface#194] opened 2018-06-06 12:42 UTC
There is no hook for fan control in the thermal controllers:
```
cd /sys/class/thermal
cat cooling_device*/type
Processor
Processor
Processor
Processor
intel_powerclamp
```

No cooling device of type "fan" is listed.

Do you think it would be possible to add it to the kernel? I was thinking maybe it is like the cameras, that they need some development to properly support. Or are they outside of reach of the kernel?

**Comment by jakeday** [comment] 2018-06-07 02:32
This is due to the lack of thermal support. That will be added with the acpi modules I'm working on.

**Comment by Lukeaton** [comment] 2018-08-16 03:31
I just installed Pop !_os on my 15" SB2. it had the gtx 1060 activated and fans where running. Temperatures where really good.

I tried installing your latest kernel after that, however it had some weird boot issues.(I am no Linux pro hence not providing logs or completely understanding the boot issue.)

I have gone back to Ubuntu 18.04 and your kernel due to this issue and the loss of touchscreen.

**Comment by dotvezz** [comment] 2018-08-16 11:14
@Lukeaton 

The GTX 1060 activates and fans spin regardless, in my experience -- but the 1060 throttles to 134MHz because the driver *doesn't know* the fans are running. When I try to load anything using Optirun, for example, it's basically unusable. Were you able to confirm that this wasn't happening for you?

**Comment by ZHG2017** [comment] 2018-10-25 19:41
Hi, may I inquire if there are already any prototyped correction for this issue ? I just wonder if the laptop will get overheated without any correct fan control.

**Comment by dotvezz** [comment] 2018-10-26 11:51
From what I can tell, at least the firmware does spin up all the fans based
on sensor data, so I've never had thermal issues.

**Comment by ZHG2017** [comment] 2018-10-26 15:46
@dotvezz OK, I see, thank you for the information.

**Comment by phunyguy** [comment] 2018-11-14 22:12
Since it appears the firmware is doing its job in kicking the fans on, and it's the driver that gets confused, is there a way, via settings, to turn that throttling off?  Or is that dangerous?

**Comment by qzed** [comment] 2018-11-14 22:40
It shouldn't be dangerous, just drain your battery faster. There's some information on disabling the dGPU [here](https://www.reddit.com/r/SurfaceLinux/comments/8yth5p/surface_book_2_disable_discreet_nvidia_card/?st=jjod9sj3&sh=f5a10622). I've currently blacklisted the nvidia/nouveau modules and written a [small module](https://github.com/qzed/linux-surfacebook2-mshw0153) that at the moment does nothing more than (basically) the same as in the reddit post linked above (via the what I think is the intended ACPI function for disabling the dGPU) when it's getting loaded.

**Comment by phunyguy** [comment] 2018-11-14 23:13
If you mean disabling the nvidia card, I absolutely do not want to do that, lol. Unless I am misunderstanding....

**Comment by qzed** [comment] 2018-11-14 23:38
@phunyguy disabling as in turning it/power to it off. I'm not aware of any other option to stop it heating up/consuming needlessly power. Considering that you won't be able to do something useful with it otherwise at the moment, since it immediately will throttle, it's not that bad of an option. Sure, you won't be able to run e.g. CUDA stuff on the integrated Intel GPU, but that won't work well with the Nvidia GPU throttling either. Sadly, playing games is probably also not working well on either of the GPUs at the moment.

Also this has nothing to do with Gnome, XOrg/Wayland should automatically use the Intel GPU when you've blocked the Nvidia drivers.

**Comment by phunyguy** [comment] 2018-11-15 00:07
@qzed, thanks.  It's a total bummer.  I got this laptop as my primary work machine (from work, so I at least didn't have to pay for it), just so I can play games on it with a dual boot windows/linux system.  Also, I keep seeing people mentioning it "throttling immediately".  That's actually not the case for me.  Sometimes I can even get 10-15 minutes of good  gaming in before it throttles even once, but most of the time it's ~5 minutes, with ~1 minute of throttle time before it kicks back up to full speed.

**Comment by qzed** [comment] 2018-11-15 07:50
@phunyguy yeah, I really wish I could tell you something different...

**Comment by qzed** [comment] 2018-12-26 17:00
Has anyone currently set up optimus/switcheroo and is willing to test if [this](https://github.com/qzed/linux-surface/releases/tag/v4.18.20-pre2) kernel makes any difference? This implements the ACPI module required for thermal events, but there might still be more stuff missing.

**Comment by versipellis** [comment] 2018-12-26 17:11
I have Optimus set up through Bumblebee I'd be happy to test.

**Comment by qzed** [comment] 2018-12-26 20:40
Awesome, just install the kernel and check if the GPU still downclocks/fans don't ramp up under some (extended) 3D load.

**Comment by jakeday** [comment] 2018-12-28 19:46
This is working with the latest builds after the changes are merged in.

**Closed by jakeday** 2018-12-28 19:46 UTC
Labels: surface-acpi module required

**Comment by phunyguy** [comment] 2019-01-26 23:21
This actually isn't working for me.  I have a self-compiled 4.18.20 kernel with the patches applied, and the surface-acpi module enabled. It still downclocks severely.. What am I doing wrong? 

# lsmod | grep surface
surfacepro3_button     16384  0
surface_acpi           36864  0

**Comment by hadrienk** [comment] 2019-01-27 12:20
> This actually isn't working for me. I have a self-compiled 4.18.20 kernel with the patches applied, and the surface-acpi module enabled. It still downclocks severely.. What am I doing wrong?
> 
> $ lsmod | grep surface
> surfacepro3_button 16384 0
> surface_acpi 36864 0

I can confirm as well. The output of nvidia-smi shows: 

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 415.27       Driver Version: 415.27       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1050    Off  | 00000000:02:00.0 Off |                  N/A |
| N/A   28C    P8     8W /  N/A |      0MiB /  2002MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

**Comment by hadrienk** [comment] 2019-01-27 15:35
Actually, looking at tear out pictures of the surface book 2 it seems there's only one fan, connected to the cpu and cards via a heat sink.

The result of `sensors` does not report any fan information either. I have tried to trigger the fan on windows but couldn't manage so far. I will give it another go later. 

When compiling the linux kernel I've noticed that the frequency on the CPUs throttles to 400Mhz after a while, more or less at the moment the temperatures of the core max up to > 100 (C). 

Has anyone observed the same behavior?

**Comment by qzed** [comment] 2019-01-27 21:49
With regards to the GPU only: Haven't tried it myself yet as I haven't had any time to do so, but [some guy on reddit](https://www.reddit.com/r/SurfaceLinux/comments/ad684r/surface_book_2_is_the_perfect_linux_laptop_thanks/edt26ja) apparently managed to get it working.

**Comment by qzed** [comment] 2019-01-27 21:57
@hadrienk With regards to the fans: I'm not sure if they are directly controllable at all. Also it depends on the model (13" vs. 15" and with/without GPU) what fans you have. The 13" has no fan in the clipboard part, which means the CPU is completely passively cooled. If you have a model with a GPU, there's also a fan in the base for that.

On the ACPI side I haven't found anything related to fan control, only the temperature readings (I might have missed something and I'm going to look over that again when I find some time). One interesting ACPI thing I also wanted to play with is power management: There seems to be a configurable power-limit on the CPU, basically there seems to be an interface which could allow us to do similar things as via Intel XTU on windows.

**Comment by qzed** [comment] 2019-01-29 18:35
> With regards to the GPU only: Haven't tried it myself yet as I haven't had any time to do so, but some guy on reddit apparently managed to get it working.

Okay, so I got this working, at least mostly. I am able to run stuff (at least glxgears) on the dGPU via bumblebee and the latest nvidia (official) driver. Seems to run fine, the GPU fan ramps up properly and temps are stable at about 56°C while above 1200fps. If anyone can tell me how I'd go about monitoring the GPU clock, I'd be happy to check that too (same if you got some other good validation methods).

The thing I didn't get to work is bbswitch. Maybe we need to implement some custom stuff for this (not hard to do, basically the start is already in [this](https://github.com/qzed/linux-surfacebook2-mshw0153) repo). Also you can currently do that via a simple ACPI mehtod call (e.g. via the acpi_call kernel module). There's also an [issue](https://github.com/Bumblebee-Project/bbswitch/issues/168) on the bbswitch repo about this. I'm not sure if this can be integrated there, would certainly be nice if it could, due to the whole ecosystem that's already existing around it.

**Comment by lynscott** [comment] 2019-02-23 04:05
@qzed How did you get the fans/readings working? I'm replicating with a 410 driver, the fans seem to come on but the temp never drops below 64(C). Testing with glxgears but I will try with a more advanced gpu test also. I can verify it is working via nvidia-smi though. I just want to make sure its not under clocking to death or over heating.


![nv410](https://user-images.githubusercontent.com/29384350/53281422-002afb80-36dd-11e9-9cb4-1c2848bc2dd3.png)

**Comment by qzed** [comment] 2019-02-24 01:36
@lynscott I get temps at around 57°C in the long run, max 59°C. The fans got a bit louder after it hit 58°C for the first time, seems like they're kicking in a bit late. The difference in temperature might be because I have the 1050 variant (13"). Clocks are for me stable at 1683MHz, you can check that via `nvidia-smi dmon`.

**Comment by qzed** [comment] 2019-04-11 22:44
A small update: I'm currently working on performance-states, which should largely fix the throttling (i.e. the thing you can control via the performance-slider on Windows). Should be done soon, details are [here](https://github.com/qzed/linux-surfacegen5-acpi/issues/18), if you're interested,
