### ISSUE TITLE
Surface Book (first gen) screen detach triggers power button...

### ISSUE THREAD

**Issue by brendandburns** [jakeday/linux-surface#282] opened 2018-10-27 04:31 UTC
For some reason, with recent kernels whenever I detach my screen the power button clicks repeatedly.

Happy to try to debug, but not sure where to look. ACPI events?

Thanks!

**Comment by sorsok** [comment] 2018-11-01 10:33
I'm experiencing this issue too

**Comment by brendandburns** [comment] 2018-12-06 06:40
fwiw, I "fixed" this by disabling "shutdown on power button" in the OS...  The button still triggers, but it doesn't try to shutdown my machine now.

(of course this also disables the hardware power button, but I'm ok with that tradeoff...)

**Comment by qzed** [comment] 2018-12-27 23:03
Duplicate of #224, if you can provide me a DSDT/acpidump, I'll look into it.

**Closed by qzed** 2018-12-27 23:03 UTC
