### ISSUE TITLE
Surface Pro 4 pen and touch not working after a random amount of time on ubuntu 16.04 LTS 

### ISSUE THREAD

**Issue by GammaPi** [jakeday/linux-surface#186] opened 2018-05-24 08:17 UTC
Pen and touch not working after a random amount of time on ubuntu 16.04 LTS 

I've tested on both Surface Book and Surface Pro 4, and it turns out that the problem only occurs on Surface Pro 4, on Surface Book it works very well!

I also encountered the problem of WIFI dropping on Ubuntu 16.04 LTS , but finally fixed it simply by disabling wifi power saving. ([Check issue 163](https://github.com/jakeday/linux-surface/issues/163)) (I offered this solution in the comment). 

So I'm thinking maybe the solution to the problem would be disabling power saving for pen and touch. 
But the problem is, I don't know how to do it, or even whether there is such option present in the driver.

**Comment by ardynn** [comment] 2018-05-27 11:51
I'm getting that on my Surface Book with Performance Base running Debian Stretch. It seems it can be fixed for a bit by rotating the screen or moving a bluetooth mouse, but after a couple of minutes it stops responding. The more times I tilt the screen to fix the problem, the less time before the pen stops responding next time.

If anyone's found a fix I'd be grateful to know how to implement it.

**Comment by realSpok** [comment] 2018-05-29 08:34
I have developed an ugly workaround with the hardware buttons of the surface pro 4, for when I am in tablet mode (with no keyboard handy), and touch crashes. The trick was to bind a sequence of volume up and down presses within a certain timeframe to trigger a "reset IPTS module" command.

With [acpid ](https://wiki.archlinux.org/index.php/acpid), I am triggering a volup.sh and voldown.sh on the respective button presses.

volup.sh and voldown.sh each contain the same code, that counts the number of volup.sh and voldown.sh processes active in the system, and reset IPTS module if more than 1 of each:

`#!/bin/bash
if [[ `ps -e | grep voldown.sh | wc -l` -gt 1 ]] && [[ `ps -e | grep volup.sh | wc -l` -gt 1 ]]
then
	#This line is a gnome notification that we are resetting IPTS
	sudo -u spok DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send 'Resetting IPTS' '.'
	#Those 2 lines reset the driver
	sudo modprobe -r intel_ipts
	sudo modprobe intel_ipts
else
	#This is the time frame for the up-down sequence to be registered
	sleep 2
fi 
`

**Comment by ardynn** [comment] 2018-06-01 13:06
Thanks very much. Any chance you could make a quick idiot-proof guide or maybe point me to the bit of the arch wiki I should pay attention to?

**Comment by realSpok** [comment] 2018-06-04 11:49
I have linked the Arch linux wiki ACPID page : https://wiki.archlinux.org/index.php/acpid, you should first have a look into this. ACPID is a utility that can trigger events and script upon certain hardware conditions. Here, when we press the volume buttons.
Create 2 files on your system, `volup.sh` and `voldown.sh`, put the script above in each of them and make them executable (`chmod +x`)
Once you have installed acpid, you can modify the following script:
`/etc/acpi/handler.sh`
To trigger the `volup.sh` and `voldown.sh` when you press the respective volume buttons. In my file this looks like this (update your paths as required):
```
    button/volumeup)
             /home/spok/Documents/ScriptsSurface/volup.sh&
         ;;
     button/volumedown)
             /home/spok/Documents/ScriptsSurface/voldown.sh&
         ;;
```

Then a quick (within 2 seconds) volume up  + volume down press should trigger the reset IPTS event and restore the touch functionnality.

**Comment by jakeday** [comment] 2018-06-07 02:35
Duplicate of #171.

**Closed by jakeday** 2018-06-07 02:35 UTC
