### ISSUE TITLE
Surface Pro3  pm-suspend cannt be waken up

### ISSUE THREAD

**Issue by Gunkkk** [jakeday/linux-surface#201] opened 2018-06-15 04:55 UTC
Touch my power button it goes into the suspend mode and will be automaticly waken up immediately.
I install the pm-utils and it can be in suspend while i can not call it back even start laptop_mode.
How can i solve it?
Thanks!

**Comment by jakeday** [comment] 2018-06-28 22:36
@Gunkkk I'm really struggling to understand what your issue is. Can you please elaborate?

**Comment by Gunkkk** [comment] 2018-06-29 11:32
@jakeday 
Sorry for  my poor English!
With the pm-utils, my surface can be suspended.However,i can't call it back(keep black).

**Comment by jakeday** [comment] 2018-06-30 19:55
@Gunkkk Gotcha, then this is a duplicate of #166. Can you post a dmesg log there?

**Closed by jakeday** 2018-06-30 19:56 UTC
