### ISSUE TITLE
[Surface Dock] Ethernet does not work

### ISSUE THREAD

**Issue by geoffholden** [jakeday/linux-surface#259] opened 2018-10-04 11:48 UTC
I just upgraded to your 4.18.11 release and the ethernet on the surface dock fails again. I just get a ton of:
r8152 2-3.2:1.0 enxbc8385f9e591: Tx status -71
in my logs until the system gives up on ethernet.

**Comment by daddins** [comment] 2018-10-23 00:33
me too!

**Comment by mattzuba** [comment] 2018-11-09 23:12
Looking at upstream, it seems that the Dock is no longer blacklisted in cdc_ether, but r8152 still defines it has supporting the dock, so only half of the patch made it upstream.  I haven't tried this myself yet (not in the office with my dock till next week), but try unloading (`modprobe -r r8152`) and blacklisting (`echo "blacklist r8152 > /etc/modeprobe.d/blacklist-r8152.conf`) and reboot for good measure and see if that does it?

**Comment by daddins** [comment] 2018-11-12 22:30
No Change for me with blacklisting.

**Comment by npjohnson** [comment] 2018-11-22 16:16
This has been broken since like 4.10 for me.

**Comment by drewwestrick** [comment] 2018-11-28 15:42
I can confirm this is still an issue at 4.18.16. Does anyone have a link to that upstream bug report? 

Do we also know what the latest working kernel version was? I'm hoping to take a look and see what changed to break it again (some have said it is related to USB 3.0 features/code).

**Comment by qzed** [comment] 2018-12-29 21:34
@drewwestrick As per #105, [this](https://bugzilla.kernel.org/show_bug.cgi?id=199153) should be the mentioned issue.

**Comment by qzed** [comment] 2018-12-29 22:19
I've had a look at this over the past two days and I've tracked down the error code of the `Tx status -71` and `Stop submitting intr, status -71` messages to [this](https://elixir.bootlin.com/linux/v4.18.20/source/drivers/usb/host/xhci-ring.c#L2306) line in `handle_tx_event` of the `xhci` driver. The error code `-71` is `-EPROTO`, which is caused by `COMP_USB_TRANSACTION_ERROR`. I haven't checked in detail, but as far as I can see, other error messages that can be observed like `Disable of device-initiated U1 failed` can also be tracked back to this line (at least in case of `EPROTO`).

The `handle_tx_event` function is called from an interrupt and seems to obtain the status value being mapped there directly from the xHCI controller.

Has anyone any idea what could cause this? The weird thing is that in rare instances it does work (with the r8152 driver), interestingly most often when I switch from Windows to Linux via restart without powering completely down, so I assume it's some sort of transport error rather than the client device (dock) not understanding what's being sent, i.e. receiving the wrong data. Maybe something in the initialization phase is missing/quirky?

The Windows device manager hints under `Driver node strong name` and `Inf section` that the ethernet chip is based on the `RTL8153` (thus the r8152 driver being used upstream should be the correct one), but as far as I can see it seems to be a custom version of that, as the only driver references I can see are `oem121.inf` and `msux64w10.inf`.

**Comment by qzed** [comment] 2018-12-30 03:36
According to the [xHCI spec](https://www.intel.com/content/dam/www/public/us/en/documents/technical-specifications/extensible-host-controler-interface-usb-xhci.pdf), 'USB Transaction Error' is

> Asserted in the case where the host did not receive a valid response from the device (Timeout, CRC, Bad PID, unexpected NYET, etc.).

I'm not sure how to debug this.

**Comment by qzed** [comment] 2018-12-30 17:21
usbmon and Wireshark may be a way forward. I'm currently looking at a usbmon dump and the initial communication seems to work. Although it looks like some responses are cut-off and thus requests are sometimes sent twice, not sure if that's an issue.

The first error I see is on a `CLEAR_FEATURE` response with `-ENOENT` for `U1_ENABLE`. After that, every request on the device fails with `-EPROTO`.

**Comment by qzed** [comment] 2018-12-30 19:30
Okay, so apparently `ENOENT` in the URB (USB Request Buffer) translates to `ETIMEDOUT` (at least in this specific instance, see [`usb_kill_urb`](https://elixir.bootlin.com/linux/v4.18.20/source/drivers/usb/core/urb.c#L695) and [`usb_start_wait_urb`](https://elixir.bootlin.com/linux/v4.18.20/source/drivers/usb/core/message.c#L64)), this is also apparent when I look at the recorded timestamps (5s timeout as defined in [`usb.h`](https://elixir.bootlin.com/linux/v4.18.20/source/include/linux/usb.h#L1829)). I've also tried a few different scenarios (switching directly from Windows to Linux, plugging in the dock for the first vs. second time) and got it to fail first on different control requests. It's always failing with `-ENOENT` first, after which all subsequent requests fail with `-EPROTO`. Guess we have a pattern.

**Comment by qzed** [comment] 2018-12-30 20:39
Alright, seems like this is a power-management issue again. Just tried with only the `USB_QUIRK_NO_LPM` quirk, and that seems to do the trick. Writing a PR now.

**Closed** 2018-12-30 23:08 UTC
Labels: A-Dock

**Comment by drewwestrick** [comment] 2019-01-02 13:42
@qzed Nice work on this! Tested the latest code with your merge and so far the Ethernet is working great.

**Comment by jpeletier** [comment] 2019-01-15 14:59
@qzed @jakeday  Awesome work!! this is my first message over Ethernet with my SB2.

**Comment by gombosg** [comment] 2019-05-25 16:30
Wow! This also solved the same issue with the Dell DA200 USB3 dock which had the same errors. Is a kernel patch the only proper solution?

**Comment by qzed** [comment] 2019-05-25 20:07
There's currently a patch on the way for the Surface Dock (https://www.spinics.net/lists/stable/msg304865.html). You'd probably have to do the same for your dock, but since it doesn't seem to be powered externally, I'm not sure about potential drawbacks (unfortunately I don't know much about this stuff). You might want to discuss this with one of the Linux usb-core developers or on the usb-core mailing-list.
