### ISSUE TITLE
SP4 Touch Screen/pen stops working after a few minutes

### ISSUE THREAD

**Issue by scotty86bne** [jakeday/linux-surface#76] opened 2018-01-20 01:06 UTC
Hi Jakeday.
Firstly, many thanks for your work on this. It's sincerely appreciated. You've made my SP4 useful again!

The issue I'm seeing is that after a minute or so of using the touch screen or pen, the touch stops working. Only recovered from a system reboot.  Running Mint 18.3 on SP4 kernel 4.14.13-surface compiled from source. I've followed your instructions re the installation of i915 drivers.

Obviously it's likely to be the IPTS driver crashing.
dmesg doesn't appear to show anything relevant though.  I'm out of my area of knowledge with solving this issue. Any suggestions on what I could do?

Just saw your reply to the audio jack issue. Perhaps I should upgrade to 4.14.14?

Thanks,
Scotty

**Comment by jakeday** [comment] 2018-01-20 01:12
@scotty86bne This would be a duplicate of #31 which points out that you can also fix it by rotating the screen. I'm not able to reproduce it the issue, and I don['t see any issues from the recent logs. My guess is just that the IPTS firmware is being weird. Maybe try one of the other sets?

**Closed by jakeday** 2018-01-20 01:12 UTC
