### ISSUE TITLE
Surface Pro 4: Wifi drops after a random amount of time (running Arch)

### ISSUE THREAD

**Issue by realSpok** [jakeday/linux-surface#84] opened 2018-02-02 17:29 UTC
I have an issue on SP4 running Archlinux 4.14.15-1-surface4
https://aur.archlinux.org/packages/linux-surface4/

The wifi drops after a random amount of time and I have to reboot.
I tried 
sudo modprobe -r mwifiex_pcie
sudo modprobe -r mwifiex
sudo modprobe -r cfg80211
sudo modprobe mwifiex_pcie
sudo modprobe mwifiex
sudo modprobe cfg80211

And restarting wpa_supplicant and networkmanager, but it doesn't solve the issue.

**Comment by demlow** [comment] 2018-02-02 17:46
Try: sudo grep "mwifiex_pcie.*FW is in bad state" /var/log/messages
If there are matching entries, the Marvell firmware has hung and a reboot is needed; there is no way to reload/restart it. There is no kernel patch yet and updating the Linux mrvl firmware and the Windows UEFI firmware doesn't help.

This only seems to occur on SP4s manufactured in early 2017 and perhaps late 2016. You can tell the manufacture date via the system serial number (printed on the back, or "sudo dmidecode -t system | grep Serial"). The block of three digits before the ending "53", e.g., "704" from 20426**704**53, tells the year (7 = 2017, etc.) and week (04 = week 4) of manufacture. Please post your serial number and whether you are seeing the kernel message above.

**Comment by realSpok** [comment] 2018-02-02 18:46
Thanks for the reply. This is not good news though :/
Here is my serial number: 053360460853
That would seem to be August 2016.
I have no  /var/log/messages file though. I will wait for the wifi to drop to see if the file is created and post the results.
Or maybe with dmesg ?

**Comment by demlow** [comment] 2018-02-02 18:59
Sorry, yes, try dmesg. It's interesting that your system is older so I am very curious if you see the FW bad state message.

**Comment by realSpok** [comment] 2018-02-02 20:11
Ok it just dropped again.
Here is the full output of dmesg after the fact:

[ 5132.936772] mwifiex_pcie 0000:02:00.0: Firmware wakeup failed
[ 5132.937137] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW in reset state
[ 5132.937187] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[ 5132.937193] mwifiex_pcie 0000:02:00.0: deleting the crypto keys
[ 5132.937197] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[ 5132.937200] mwifiex_pcie 0000:02:00.0: deleting the crypto keys
[ 5132.937204] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[ 5132.937207] mwifiex_pcie 0000:02:00.0: deleting the crypto keys
[ 5132.937211] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[ 5132.937214] mwifiex_pcie 0000:02:00.0: deleting the crypto keys
[ 5132.937217] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[ 5132.937221] mwifiex_pcie 0000:02:00.0: deleting the crypto keys
[ 5132.937224] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[ 5132.937227] mwifiex_pcie 0000:02:00.0: deleting the crypto keys
[ 5132.937265] mwifiex_pcie 0000:02:00.0: info: shutdown mwifiex...
[ 5133.047193] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[ 5133.047215] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[ 5134.164461] mwifiex_pcie 0000:02:00.0: WLAN FW already running! Skip FW dnld
[ 5134.164462] mwifiex_pcie 0000:02:00.0: WLAN FW is active
[ 5134.207353] mwifiex_pcie 0000:02:00.0: Unknown api_id: 4
[ 5134.230554] mwifiex_pcie 0000:02:00.0: info: MWIFIEX VERSION: mwifiex 1.0 (15.68.7.p154) 
[ 5134.230556] mwifiex_pcie 0000:02:00.0: driver_version = mwifiex 1.0 (15.68.7.p154) 
[ 5134.231707] mwifiex_pcie 0000:02:00.0 wlp2s0: renamed from mlan0
[ 5134.255407] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
[ 5134.255533] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
[ 5134.298394] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
[ 5138.233735] mwifiex_pcie 0000:02:00.0: info: trying to associate to 'Box' bssid 44:ce:7d:23:ee:f4
[ 5138.234255] mwifiex_pcie 0000:02:00.0: CMD_RESP: cmd 0x12 error, result=0x1
[ 5138.234259] mwifiex_pcie 0000:02:00.0: info: association to bssid 44:ce:7d:23:ee:f4 failed
[ 5142.250371] mwifiex_pcie 0000:02:00.0: info: trying to associate to 'Box' bssid 44:ce:7d:23:ee:f4
[ 5142.251364] mwifiex_pcie 0000:02:00.0: CMD_RESP: cmd 0x12 error, result=0x1
[ 5142.251464] mwifiex_pcie 0000:02:00.0: info: association to bssid 44:ce:7d:23:ee:f4 failed

There is no "FW is in bad state" it seems. Maybe this is good news for me. Or the debug level is not correct. 
Interestingly, it didn't drop while I was away. Maybe this is just chance, but I think that it only drops when I am doing something on internet.

**Comment by realSpok** [comment] 2018-02-02 20:15
It seems like it is trying to reconnect after a couple seconds. But it never gets through.

**Comment by demlow** [comment] 2018-02-02 20:28
Yes, that looks different than the failure mode I initially expected (but that is not so surprising given your serial number). So this is probably not a duplicate of [](https://github.com/jakeday/linux-surface/issues/68) (which occurs on both SP2017 and SP4).

**Comment by demlow** [comment] 2018-02-02 20:29
Sorry, that last post should include a link to https://github.com/jakeday/linux-surface/issues/68.

**Comment by realSpok** [comment] 2018-02-02 20:36
Right, thanks for the feedback. Actually I saw #68 earlier, but it seemed like a different issue for a number of reasons:
- Error message is different
- It occurs on SP4 instead of SP2017
- I had the same behaviour with the previous kernel  ( I tried 4.14.2 and 4.14.15 so far)
Please let me know if you need further logs. It is easily reproducible for me.

**Comment by s8m** [comment] 2018-02-03 04:53
I have yet to give the new kernel a shot, but just FYI I am having the same issue on an SP4 where the key 3 numbers are 543 (i.e. manufactured mid to late October 2015). So I'm not sure the manufactured date is an indication of why SP4's are having this issue.

**Comment by SnowMB** [comment] 2018-02-03 08:34
I've got the same issue and my Surface Pro 4 is also from 2015 (540). So I think the @s8m is right.

**Comment by realSpok** [comment] 2018-02-03 12:09
Do you guys have the same dmesg log after a disconnect ?

**Comment by realSpok** [comment] 2018-02-03 15:11
Following up my post, I looked further for a solution, and came across something interesting [here](https://bugzilla.redhat.com/show_bug.cgi?id=1505058).
I tried an equivalent for Arch (iw instead of iwconfig):
`sudo iw dev wlp2s0 set power_save off`
This seems to work for the moment. The wifi has not dropped for more than 3 hours now.
Apparently it should prevent the wifi from going to sleep, but since suspend is not supported yet on the SP I don't think it is a problem.

**Comment by jakeday** [comment] 2018-02-03 23:17
@realSpok Just to note, my kernels have power saving turned off for wifi so that step is not required.

**Comment by realSpok** [comment] 2018-02-04 09:19
Thanks for the note. I couldn't find the command to display the current power save status of wifi, so I just set it to off. Maybe it was off already and the fact that I had not drop was a fluke.

**Comment by realSpok** [comment] 2018-02-05 12:36
I experienced another wifi drop since the last time I posted, but it was after a restart. So I found the command to show the interface power_save status at startup, and here it is for me:
`sudo iw dev wlp2s0 get power_save
Power save: on`

So 2 things: in my case I have only seen the drop when in "Power save mode on", so the settings does indeed seem to help. And next it is not enabled by default on my system. Maybe this is a feature of the AUR repository.
I am now looking for a way to enable it at startup, like it should.

**Comment by jakeday** [comment] 2018-02-06 12:44
@realSpok Can you give this another try with the latest builds I pushed? I re-compiled 4.15.1 and 4.14.17 with my updated wifi patches, so download the latest ones and give it a shot.

**Comment by realSpok** [comment] 2018-02-06 18:06
Ok. But I usually do not compile myself for Archlinux. That will have to wait for the downstream AUR repository to be updated.

**Closed** 2018-02-08 01:50 UTC
Labels: needs verification

**Comment by wurmf** [comment] 2018-08-10 07:01
I got the same issue with my Surface Pro 3 when running Fedora and Manjaro. I will try @realSpok solution and see if this fixes it. Thanks in advance!
