### ISSUE TITLE
Surface Book 2: Tight CPU spinning in ACPI and Battery Overheating

### ISSUE THREAD

**Issue by chergert** [jakeday/linux-surface#65] opened 2017-12-19 23:50 UTC
Hi!

First off, thanks for all your work here. I'm not filing this issue in expectation that you fix anything for me, but figured it might be a good place to track an issue I hope to look at (and maybe you already know the issue and would know a fix or pointer to the specific code).

While tracking down an unrelated issue, I noticed the lid state tracking has gone haywire. Here is a quick dump from Sysprof showing the spinning in ACPI handling. I assume this happened after I shut the lid at one point.

```
      SELF CUMULATIVE    FUNCTION
[   0.00%] [ 100.00%]    [Everything]
[   0.00%] [  47.15%]      [kworker/0:1]
[   0.00%] [  47.15%]        - - kernel - -
[   0.00%] [  47.10%]          ret_from_fork
[   0.00%] [  47.10%]            kthread
[   0.01%] [  47.10%]              worker_thread
[   0.01%] [  47.09%]                process_one_work
[   0.00%] [  47.04%]                  acpi_os_execute_deferred
[   0.01%] [  47.03%]                    acpi_ev_notify_dispatch
[   0.00%] [  46.86%]                      acpi_device_notify
[   0.00%] [  46.82%]                        acpi_button_notify
[   0.01%] [  46.82%]                          acpi_lid_update_state
[   0.00%] [  46.75%]                            acpi_evaluate_integer
[   0.00%] [  46.75%]                              acpi_evaluate_object
[   0.01%] [  46.61%]                                acpi_ns_evaluate
[   0.00%] [  46.28%]                                  acpi_ps_execute_method
[   0.02%] [  46.12%]                                    acpi_ps_parse_aml
[   0.58%] [  39.00%]                                      acpi_ps_parse_loop
[   0.30%] [  23.46%]                                        acpi_ds_exec_end_op
[   0.11%] [   7.35%]                                        acpi_ps_get_next_namepath
[   0.12%] [   2.56%]                                        acpi_ps_get_next_arg
[   0.40%] [   2.01%]                                        acpi_ps_create_op
[   0.24%] [   1.79%]                                        acpi_ps_complete_op
[   0.04%] [   0.55%]                                        acpi_ps_push_scope
[   0.11%] [   0.11%]                                        acpi_ps_get_opcode_info
[   0.07%] [   0.07%]                                        acpi_ps_peek_opcode
[   0.04%] [   0.06%]                                        acpi_ps_next_parse_state
[   0.05%] [   0.05%]                                        acpi_ps_append_arg
[   0.01%] [   0.04%]                                        acpi_ds_get_predicate_value
[   0.04%] [   0.04%]                                        acpi_ns_get_attached_object
[   0.02%] [   0.04%]                                        acpi_ps_pop_scope
[   0.02%] [   0.02%]                                        acpi_ps_get_parent_scope
[   0.02%] [   0.02%]                                        acpi_ps_get_next_simple_arg
[   0.02%] [   0.02%]                                        acpi_ds_exec_begin_op
[   0.02%] [   0.02%]                                        acpi_ex_truncate_for32bit_table
[   0.02%] [   0.02%]                                        acpi_ds_create_operands
[   0.02%] [   0.02%]                                        acpi_ds_result_push
[   0.02%] [   0.02%]                                        acpi_ps_get_opcode_size
[   0.01%] [   0.01%]                                        acpi_ex_opcode_2A_1T_1R
[   0.00%] [   0.01%]                                        __irqentry_text_start
[   0.01%] [   0.01%]                                        acpi_ds_exec_end_control_op
[   0.01%] [   0.01%]                                        acpi_ps_alloc_op
[   0.01%] [   0.01%]                                        acpi_ut_delete_generic_state
[   0.01%] [   0.01%]                                        acpi_ds_evaluate_name_path
[   0.01%] [   0.01%]                                        acpi_ex_opcode_1A_0T_1R
[   0.01%] [   0.01%]                                        acpi_ds_clear_operands
[   0.01%] [   0.01%]                                        acpi_ds_delete_result_if_not_used
[   0.01%] [   0.01%]                                        acpi_ps_init_op
[   0.01%] [   0.01%]                                        acpi_ps_has_completed_scope
[   0.01%] [   0.01%]                                        acpi_ds_method_error
[   0.01%] [   0.01%]                                        acpi_ds_resolve_operands
[   0.01%] [   0.01%]                                        acpi_ex_start_trace_opcode
[   0.01%] [   0.01%]                                        acpi_ns_lookup
[   0.01%] [   0.01%]                                        acpi_ut_create_generic_state
[   0.01%] [   0.01%]                                        acpi_ut_push_generic_state
[   0.01%] [   0.01%]                                        acpi_ex_resolve_operands
[   0.03%] [   5.36%]                                      acpi_ds_terminate_control_method
[   0.04%] [   1.20%]                                      acpi_ds_call_control_method
[   0.05%] [   0.17%]                                      acpi_ds_delete_walk_state
[   0.03%] [   0.10%]                                      acpi_ds_restart_control_method
[   0.05%] [   0.05%]                                      acpi_ps_next_parse_state
[   0.01%] [   0.04%]                                      acpi_ds_scope_stack_clear
[   0.03%] [   0.03%]                                      acpi_ps_get_opcode_info
[   0.00%] [   0.03%]                                      acpi_ps_cleanup_scope
[   0.02%] [   0.02%]                                      acpi_ps_push_scope
[   0.02%] [   0.02%]                                      acpi_ds_pop_walk_state
[   0.02%] [   0.02%]                                      acpi_ex_start_trace_opcode
[   0.01%] [   0.01%]                                      acpi_ex_stop_trace_method
[   0.01%] [   0.01%]                                      acpi_ps_complete_op
[   0.01%] [   0.01%]                                      acpi_ps_create_op
[   0.01%] [   0.01%]                                      acpi_ns_get_attached_object
[   0.01%] [   0.01%]                                      acpi_ds_exec_end_op
[   0.01%] [   0.01%]                                      acpi_ps_get_next_namepath
[   0.01%] [   0.01%]                                      acpi_ns_delete_namespace_subtree
[   0.01%] [   0.01%]                                      kfree
[   0.01%] [   0.01%]                                      acpi_ut_release_owner_id
[   0.01%] [   0.03%]                                    acpi_ds_create_walk_state
[   0.00%] [   0.02%]                                    acpi_ds_begin_method_execution
[   0.01%] [   0.01%]                                    acpi_ds_terminate_control_method
[   0.00%] [   0.01%]                                    acpi_ds_init_aml_walk
[   0.01%] [   0.01%]                                    acpi_ex_release_all_mutexes
[   0.01%] [   0.01%]                                    acpi_ds_delete_walk_state
[   0.01%] [   0.01%]                                    acpi_ps_cleanup_scope
[   0.01%] [   0.01%]                                    acpi_ns_get_attached_object
[   0.00%] [   0.01%]                                    acpi_ps_delete_parse_tree
[   0.01%] [   0.01%]                                    acpi_ds_restart_control_method
[   0.01%] [   0.01%]                                    acpi_ds_pop_walk_state
[   0.01%] [   0.01%]                                    acpi_ds_scope_stack_clear
[   0.01%] [   0.01%]                                    acpi_ds_clear_implicit_return
[   0.00%] [   0.01%]                                    acpi_ut_create_integer_object
[   0.00%] [   0.01%]                                    acpi_ps_create_scope_op
[   0.01%] [   0.01%]                                    acpi_ds_get_current_walk_state
[   0.00%] [   0.12%]                                  acpi_ns_get_node
[   0.00%] [   0.08%]                                  acpi_ex_exit_interpreter
[   0.02%] [   0.04%]                                  acpi_ut_match_predefined_method
[   0.00%] [   0.03%]                                  acpi_ex_enter_interpreter
[   0.01%] [   0.02%]                                  acpi_ns_get_normalized_pathname
[   0.01%] [   0.01%]                                  acpi_ns_check_return_value
[   0.01%] [   0.01%]                                  acpi_ut_get_next_predefined_method
[   0.01%] [   0.01%]                                  acpi_ps_update_parameter_list
[   0.00%] [   0.06%]                                acpi_ex_enter_interpreter
[   0.00%] [   0.04%]                                acpi_ex_exit_interpreter
[   0.00%] [   0.01%]                                acpi_ut_remove_reference
[   0.01%] [   0.01%]                                kfree
[   0.00%] [   0.01%]                                acpi_os_allocate_zeroed
[   0.01%] [   0.01%]                                acpi_ut_copy_iobject_to_eobject
[   0.01%] [   0.01%]                                acpi_ns_get_attached_object
[   0.00%] [   0.01%]                                acpi_ut_get_object_size
[   0.00%] [   0.06%]                            acpi_lid_notify_state
[   0.01%] [   0.01%]                          acpi_lid_notify_state
[   0.00%] [   0.03%]                        acpi_video_bus_notify
[   0.01%] [   0.01%]                        acpi_lid_update_state
[   0.01%] [   0.15%]                      acpi_bus_notify
[   0.01%] [   0.01%]                      acpi_video_bus_notify
[   0.01%] [   0.01%]                    kfree
[   0.04%] [   0.04%]                  _raw_spin_lock_irq
[   0.03%] [   0.03%]          __switch_to
[   0.01%] [   0.01%]          __switch_to_asm
[   0.01%] [   0.01%]          native_load_tls
```

**Comment by jakeday** [comment] 2017-12-24 20:32
@chergert Can you please report if this is still an issue with 4.14.8?

**Comment by chergert** [comment] 2017-12-25 09:43
Yes, same issue with 4.14.8.

**Comment by Fabyao** [comment] 2017-12-29 12:43
I can confirm this is an issue with 4.14.8. My surface book 2 runs very hot. Again not expecting you to fix it. However I would appreciate any pointers to help me understand the issue. Thanks for your awesome kernel

**Comment by jakeday** [comment] 2018-02-02 03:43
This is actually the same issue as #83.

**Comment by jakeday** [comment] 2018-02-02 03:56
This is targeted to be fixed in the upcoming 4.15 release.

**Comment by jakeday** [comment] 2018-02-03 23:18
@chergert @Fabyao My 4.15.0 build is up now. Can you give it a try?

**Comment by chergert** [comment] 2018-02-04 02:51
It looks like the spin loop is still an issue from ACPI lid state tracking.

```
      SELF CUMULATIVE    FUNCTION
[   0.00%] [ 100.00%]    [Everything]
[   0.00%] [  58.63%]      [kworker/0:3]
[   0.00%] [  58.63%]        - - kernel - -
[   0.00%] [  58.11%]          ret_from_fork
[   0.00%] [  58.11%]            kthread
[   0.01%] [  58.11%]              worker_thread
[   0.01%] [  58.09%]                process_one_work
[   0.01%] [  58.08%]                  acpi_os_execute_deferred
[   0.01%] [  58.06%]                    acpi_ev_notify_dispatch
[   0.00%] [  57.78%]                      acpi_lid_update_state
[   0.00%] [  57.72%]                        acpi_evaluate_integer
[   0.01%] [  57.72%]                          acpi_evaluate_object
[   0.00%] [  57.57%]                            acpi_ns_evaluate
[   0.01%] [  57.11%]                              acpi_ps_execute_method
[   0.04%] [  56.99%]                                acpi_ps_parse_aml
[   0.76%] [  49.00%]                                  acpi_ps_parse_loop
```

**Comment by jakeday** [comment] 2018-02-04 03:26
@chergert Looks like this is an issue with properly reading the states from the dsdt files as well, which is handled on Windows through the ACPI Notify driver. It works a little different on these devices, and I'm writing a driver for mshw0091 for acpi over i2c to support this. This seems to be causing most the the bugs we are still seeing and it's my top priority right now.

**Comment by chergert** [comment] 2018-02-04 04:27
Exciting! Let me know if there is anything I can do to help or get you any information you need or testing.

**Comment by dangerm0us** [comment] 2018-02-07 23:09
Colour me excited also!

**Comment by dangerm0us** [comment] 2018-02-14 21:49
I just couldn't wait and went ahead and tried 4.15 last night on my SB2 13" w/ Linux Mint 18.3.

I have also suffered the issue described.  My SB2 turned into a frying pan!  I think I nailed the battery in under an hour.  Woops.

**Comment by dh-harald** [comment] 2018-03-04 13:48
I don't know, is it the new driver or not, but on the latest kernel (4.15.7) on SB2, I could fix the throttling with the following settings:
scaling_min_freq: 400000
scaling_max_freq: 4200000
scaling_governor: powersave

**Comment by jakeday** [comment] 2018-03-04 14:34
@dh-harald Yes, that is due to the new driver. You have the ability to set cpu scaling now that power management is enabled.

**Closed by jakeday** 2018-03-04 14:34 UTC
Labels: acpi notify module required
