### ISSUE TITLE
Surface Book 2 Battery Drain

### ISSUE THREAD

**Issue by Lukeaton** [jakeday/linux-surface#209] opened 2018-06-27 08:42 UTC
Hey there. Fairly new to Linux. Dual booting Ubuntu 18.04 LTS and Windows 10 on Surface Book 2 15".
Using kernel linux-libc-dev_4.17.1-surface-linux-surface-3_amd64.deb.

The issue is that running on windows I get almost 2 days of battery. When using Linux only get around 3-4 hours screen on time. Using same apps. Atom, Chrome and streaming music.
I am more then happy to provide more details if needed. i.e. logs etc, I just might need some help on how to provide those.

Same issue with previous kernels.

**Comment by remingtonlang** [comment] 2018-06-27 17:08
@lukeaton yes that’s fairly common for Linux irrespective of device or the kernel.. Linux just isn’t as efficient on a battery.

It’s also a fairly commonly discussed topicZ I don’t think this is an appropriate case for Jake, google around and youlll find lots of little tips and tricks to get more life out of your battery

**Comment by qzed** [comment] 2018-06-27 21:43
While this is common, I'd still say we should look if we can improve this. What I noticed is that the base gets warmer than in windows, so this might be something related to GPU or the battery, also the fan spins all the time.

**Comment by Lukeaton** [comment] 2018-06-28 02:30
@remingtonlang. I am fairly new to Linux, but not to using Google to search for things. I haven't found a specific answer to this, hence posting here.

I'm not demanding anything from anyone. Just trying to discuss an issue and a possible solution if at all possible. More than willing to do work on my end to help in any way I can. I just think that going from around 17hrs battery on windows to about 4 on Linux is far too great a drop. I have just started a web development bootcamp and need Linux, as I refuse to use Apple products. So I need to find a way to squeeze at least another 4hrs out of this.

**Comment by oleid** [comment] 2018-06-28 07:44
@Lukeaton Not sure about SB2, but powertop helps a little with my SP4: https://01.org/powertop/

**Comment by Lukeaton** [comment] 2018-06-28 10:09
Thanks @oleid . I will have a look at that.

**Comment by jakeday** [comment] 2018-06-28 22:33
It's actually a lot better than it used to be! The problem is that the fans and thermals are not fully mapped yet, so the proper regulation isn't happening. Been working on these as well as fully supporting the MSHW0084, MSHW0091, and MSHW0126 and really want to have them done soon.

**Comment by Lukeaton** [comment] 2018-06-29 01:48
Awesome.

I am in awe at you @jakeday .

I am learning to be a web developer and I find that hard enough.

You should remind yourself how talented you are.

**Comment by jakeday** [comment] 2018-06-30 20:00
I'm going to go ahead and close this as it's being handled in #194

**Closed by jakeday** 2018-06-30 20:00 UTC
