### ISSUE TITLE
Pinch to zoom on touchscreen on Surface pro 4 with linux not working

### ISSUE THREAD

**Issue by navneet92** [jakeday/linux-surface#19] opened 2017-10-27 11:44 UTC
I am running your linux 4.12 kernel on surface pro4, i got everything  working i.e. single touch on screen, multi touch type cover, keyboard etc. But i could not get 2 fingers pinch to zoom on touchscreen to work. 

I tried changing the mode to multitouch by:
echo 1 > /sys/kernel/debug/ipts/mode. 
But my touchscreen stopped working from that.

**Comment by peter-sa** [comment] 2017-10-27 19:40
I believe that I have some more patches that make the pen/multitouch mode work. I will make a pull request with them in the next day or two.

**Comment by Yanim** [comment] 2017-10-31 12:46
How is the patch doing? Or any other way to too fix this/pen. ;)

**Comment by Yanim** [comment] 2017-10-31 12:48
to fix*

**Comment by peter-sa** [comment] 2017-10-31 18:56
Hi Yanim and all,

I am sorry for the delay.  Since my kernel is a bit different from jakeday's, I wanted to test the ported patches separately from my own kernel, which I use daily but has a slightly different focus from jakeday's. I planned to test the ported patches on hardware over the weekend, but unfortunately did not have time.  I will push the untested patches in an hour or so, so that interested parties can try them, and I will try to test/pull request tomorrow.

**Comment by jakeday** [comment] 2017-10-31 19:22
@peter-sa I wasn't planning on doing any additional work for multitouch until after 4.14 is official. If you have some patches that might work, I would greatly appreciate it! I don't mind testing them either!

**Comment by Yanim** [comment] 2017-11-01 00:58
Do any of you know what this guy did https://www.youtube.com/watch?v=Z0bIYOf3_rY to get his setup working? His kernel is from the arch AUR and is based on your kernel afaik. He provides some **very** vague instructions in the description but I can personally not make sense of them. 

He writes "For the pen, I had to find its address via less /proc/bus/input/devices, and then change the last section in to match "ipts 1B96:006A Pen" to recognize the n-trig digitizer."

**Comment by peter-sa** [comment] 2017-11-01 01:18
Hi Yanim,

 I think this may refer to making the x11 driver (Wacom?) bind to the input device, rather than to the kernel driver which we are working on. Will you be around in ~30m? I will send my patches in that time.and am happy to help walk you through applying/troubleshooting them.

**Comment by peter-sa** [comment] 2017-11-01 01:51
@Yanim @jakeday I have pushed three patches that I believe have the most important of my modifications to the i915 driver here: https://github.com/peter-sa/linux-sb/commits/for-jakeday.  I have not tested with these patches merged on this kernel.  If one you would not mind testing, that would be great.

@jakeday I am glad that this is helpful - I have just recently discovered that you are also maintaining IPTS patches after working on them on my own for some time.  I hope that these modifications are useful!

I also have some other changes that I don't believe increase the stability of the driver, and have not integrated/pushed yet.  These include replacing the execlists_context functions that were used with the new-style engine->context_pin/context_unpin functions and the complete removal of the doorbell reacquisition thread.  I believe both of these changes can add to the maintainability/potential upstreamability of the driver.  The second one in particular I am unsure about, but I believe that the GuC doorbell management code is stable enough now that it is okay to handle the doorbell in `guc_init_doorbell_hw`, and I have not observed any doorbell related reliability issues.  However, I cannot be completely sure that there are not some edge cases where the old approach might have worked better.

Also I have noticed that sometimes - usually after a number of suspend/resume cycles - the ME starts reporting failure on a number of commands and touch/pen stop working.  Unfortunately, I have not yet had much success debugging this without the spec.

If anyone else here does work on DRM, I would greatly appreciate any tips on which direction to move in towards upstreamability.  I assume that a general interface for GuC clients from other modules is roughly the direction to move in, but I'm not sure what the best way to handle all of the gem and vma details that the driver needs is, or how upstreamable even that would be.

**Comment by jakeday** [comment] 2017-11-01 13:06
@peter-sa Yeah, I have all of those changes in my 4.13 build. They introduce some strange behavior in 4.14, which is why I held off on them for now. Also, none of those changes have anything to do with multitouch or pen. Did you have other patches for those you were going to submit?

**Comment by peter-sa** [comment] 2017-11-01 19:36
@jakeday Just for my own understanding, I am curious about one thing that you mentioned there: you say "none of those changes have anything to do with multitouch or pen".  My understanding is that multitouch/pen is the only ipts codepath that uses the GuC command submission/GFX (in single-touch mode, the ME does all the processing), and so all code fixes that are in the i915/GuC command submission part of the driver are part of the multitouch/pen code.  Also the `i915_gem_object_get_pages_phys` change is, while not technically part of the driver, a codepath that is used by the driver, and definitely affects the driver's ability to allocate its resources.  I am interested to know if anything there is wrong so that I can work more effectively on the next version of the driver.

Also, did you have https://github.com/peter-sa/linux-sb/commit/d229472e1783e028819f9348650d0fae1c33ddf6 in 4.13? For me, this was the most important one as IPTS would sometimes allocate non-power-of-two things through gem, and I did not notice it when I was looking through your ipts patches from 4.13.

**Comment by peter-sa** [comment] 2017-11-01 19:38
@Yanim what hardware do you have btw?  Although I know that these patches do not fix the issue for some people, I would appreciate it if you could test the kernel that I pushed and let me know whether or not it works/send logs, so that I can compare logs between a number of systems both where it works and where it doesn't.

**Comment by jakeday** [comment] 2017-11-01 23:39
Closing this one as it's, code wise, a duplicate of #8

**Closed by jakeday** 2017-11-01 23:39 UTC
